import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),

    title: "The Book Of Life",
    author: "J Krishnamurti",
    price: 250,
    nonfiction: "nonfiction",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/61WVRpAeALL._AC_UY218_.jpg",
    rating: 2,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "Yersternight",
    author: "Cat Winters",
    price: 400,
    horror: "horror",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/81AnXo6DwCL._AC_UL320_.jpg",
    rating: 4.5,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "Yaar Papa",
    author: "Divya Prakash Dubey",
    price: 550,
    fiction: "fiction",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/71UchDE8PQL._AC_UL320_.jpg",
    rating: 3.5,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "Iron Flame",
    author: "Rebecca Yarros",
    price: 1000,
    fiction: "fiction",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/91vTsJScPSL._AC_UY218_.jpg",
    rating: 5,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "That Night",
    author: "Nidhi Upadhyay",
    price: 750,
    horror: "horror",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/81b1PP4RK1L._AC_UY218_.jpg",
    rating: 4.7,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "Atomic Habits",
    author: "James Clear",
    price: 800,
    nonfiction: "nonfiction",
    isAddedToCart: false,
    isWished: false,
    image:
      "https://m.media-amazon.com/images/I/51-nXsSRfZL._SX328_BO1,204,203,200_.jpg",
    rating: 4.5,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "It Follows You",
    author: "Keran Pantth Joshi",
    price: 900,
    horror: "horror",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/81XZWZfinrS._AC_UY218_.jpg",
    rating: 3.9,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "Greatest Work Of Jane Austen",
    author: "Jane Austen",
    price: 950,
    fiction: "fiction",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/51sa8AB3vLL._SY445_SX342_.jpg",
    rating: 3.9,
    quantity: 1,
    language: "English",
  },
  {
    _id: uuid(),
    title: "Ikigai",
    author: "Keira Miki",
    price: 450,
    nonfiction: "nonfiction",
    isAddedToCart: false,
    isWished: false,
    image: "https://m.media-amazon.com/images/I/81l3rZK4lnL._AC_UY218_.jpg",
    rating: 4.7,
    quantity: 1,
    language: "English",
  },
];
